# -*- coding: utf-8 -*-
"""每条 Formal 用例的机器可读验证 profile（与 expected_result 对齐）。"""

PROFILES: dict[str, str] = {
    "TC-SMOKE-001": "exec:webhook|messages:你好|checks:webhook_ok,inbound_ok,outbound≤10s,not_handoff_tpl,bot_active,task_type",
    "TC-SMOKE-002": "exec:webhook|messages:Hot70 多少钱|checks:webhook_ok,outbound≤10s,price_keywords,not_handoff_tpl,rag_tool_ok",
    "TC-SMOKE-003-LOCAL": "exec:webhook|messages:转人工|checks:webhook_ok,local_handoff,handoff_assigned,conv_listed",
    "TC-SMOKE-003-EXT": "exec:defer_ext|manual:智齿工作台,groupid,external_handoff状态",
    "TC-SMOKE-003b": "exec:handoff_then_silence|messages:在吗;还有人吗|checks:no_bot_outbound",
    "TC-SMOKE-004": "exec:use_handoff_session|manual:sendManual,WA送达,sendStatus",
    "TC-SMOKE-005": "exec:use_handoff_session|checks:session_traceable,task_type,handoff_state_m8",
    "TC-M2-001": "exec:webhook|messages:Hello|checks:webhook_ok,inbound_ok,handoff_or_faq",
    "TC-M2-002": "exec:webhook|messages:How to pre-order?|checks:webhook_ok,handoff_or_faq,task_type",
    "TC-M2-003": "exec:webhook|messages:😀👍|checks:webhook_ok,emoji_handled",
    "TC-M2-004": "exec:webhook|messages:   |checks:webhook_ok,empty_input_hint",
    "TC-M2-005": "exec:webhook|messages:>500字|checks:webhook_ok,long_text_ok",
    "TC-M2-006": "exec:webhook_multi|checks:webhook_ok,multi_inbound,session_stable",
    "TC-M2-007": "exec:webhook|messages:Hot70 多少钱|checks:webhook_ok,outbound≤10s|manual:真机WA可见",
    "TC-M2-008": "exec:metrics|corpus:kb-sample|checks:metrics_aggregate",
    "TC-M2-009": "exec:manual_only|manual:mock发送失败,error日志",
    "TC-M2-010": "exec:manual_only|manual:重复message_id",
    "TC-M5-LOCAL-001": "exec:webhook|messages:转人工|checks:local_handoff,handoff_assigned",
    "TC-M5-LOCAL-002": "exec:handoff_then_silence|messages:在吗;请问;hello|checks:no_bot_outbound",
    "TC-M5-F01": "exec:defer_ext|manual:partnerid,wa_id",
    "TC-M5-F02": "exec:defer_ext|manual:多轮FAQ后EXT,最近意图",
    "TC-M5-F03": "exec:defer_ext|manual:history_messages条数",
    "TC-M5-F04": "exec:defer_ext|manual:昵称字段",
    "TC-M5-F05": "exec:defer_ext|manual:tran_flag",
    "TC-M5-F06": "exec:defer_ext|manual:params,customer_fields",
    "TC-M5-010": "exec:defer_ext|manual:EXT后静默",
    "TC-M6-A01": "exec:defer_ext|manual:groupid",
    "TC-M6-A02": "exec:defer_ext|manual:技能组接单",
    "TC-M6-A03": "exec:defer_ext|manual:智齿坐席回传",
    "TC-M7-001": "exec:use_handoff_session|manual:sendManual纯文本",
    "TC-M7-002": "exec:use_handoff_session|manual:多行文本",
    "TC-M7-003": "exec:use_handoff_session|manual:连发3条",
    "TC-M7-004": "exec:handoff_then_silence|messages:再咨询一条|checks:no_bot_outbound|manual:坐席继续回复",
    "TC-M7-005": "exec:manual_only|manual:送达率≥20样本",
    "TC-M8-001": "exec:webhook_multi|checks:session_stable,multi_inbound",
    "TC-M8-002": "exec:webhook|messages:你好|checks:inbound_ok|manual:wa_id对照",
    "TC-M8-003": "exec:webhook|messages:Hot70 多少钱|checks:outbound≤10s,inbound_ok",
    "TC-M8-004": "exec:webhook|messages:测试关键词ABC|checks:inbound_ok",
    "TC-M8-005": "exec:webhook|messages:Hot70 多少钱|checks:task_type",
    "TC-M8-006": "exec:webhook|messages:Hot70 多少钱|checks:task_type|manual:confidence_in_steps",
    "TC-M8-007": "exec:webhook|messages:Hot70 多少钱|checks:rag_tool_ok",
    "TC-M8-008": "exec:webhook|messages:Hot70 多少钱|checks:webhook_ok|manual:WA对照",
    "TC-M8-009": "exec:use_handoff_session|checks:handoff_state_m8",
    "TC-M8-010": "exec:webhook|messages:火星上有 Hot70 吗|checks:handoff_required|manual:audit汇总",
    "TC-M8-011": "exec:manual_only|manual:error日志",
    "TC-M9-001": "exec:blocked",
    "TC-M9-002": "exec:blocked",
    "TC-M9-003": "exec:blocked",
    "TC-M9-004": "exec:blocked",
    "TC-M9-005": "exec:blocked",
    "TC-M9-006": "exec:blocked",
    "TC-M9-007": "exec:blocked",
    "TC-M9-008": "exec:blocked",
    "TC-M10-001": "exec:manual_only|manual:真机辱骂敏感",
    "TC-M10-002": "exec:webhook|messages:竞品手机怎么样|checks:webhook_ok|manual:运营口径",
    "TC-M10-003": "exec:webhook_multi|messages:Hot70 多少钱;Hot70 多少钱|manual:口径一致",
    "TC-M10-004": "exec:manual_only|manual:会话超时",
    "TC-M10-005": "exec:manual_only|manual:双端真机",
    "TC-M4-P1-001": "exec:webhook|messages:火星上有 Hot70 吗|checks:handoff_required,no_hallucination_handoff",
    "TC-M4-P1-002": "exec:webhook|messages:还有库存吗|checks:handoff_required,no_hallucination_handoff",
    "TC-M4-P1-003": "exec:webhook|messages:我的订单到哪了|checks:handoff_required,no_hallucination_handoff",
    "TC-M4-P1-004": "exec:webhook|messages:随便乱问xyz|checks:handoff_required|manual:audit汇总",
    "TC-M11-001": "exec:webhook|messages:   |checks:empty_input_hint",
    "TC-M11-002": "exec:webhook|messages:😀😀😀|checks:gibberish_hint,emoji_handled",
    "TC-M11-003": "exec:webhook|messages:asdfghjkl123|checks:gibberish_hint",
    "TC-M11-004": "exec:webhook|messages:今天天气怎么样|checks:handoff_required,no_hallucination_handoff",
    "TC-M11-005": "exec:webhook|messages:火星上有 Hot70 吗|checks:handoff_required",
    "TC-M11-006": "exec:manual_only|manual:mock转人工失败",
    "TC-M11-007": "exec:manual_only|manual:mock发送失败",
    "TC-M11-008": "exec:manual_only|manual:mock超时",
    "TC-M11-009": "exec:manual_only|manual:非文本消息",
    "TC-M11-010": "exec:webhook|messages:测试辱骂文案|checks:handoff_required|manual:礼貌回应",
    "TC-M11-011": "exec:webhook|messages:价格多少还有门店在哪|checks:clarify_multi_intent",
    "TC-M11-012": "exec:manual_only|manual:超时后再进线",
    "TC-M11-013": "exec:manual_only|manual:刷屏10条",
    "TC-M11-014": "exec:manual_only|manual:API异常文案",
    "TC-L4-001": "exec:metrics|checks:metrics_aggregate",
    "TC-L4-002": "exec:metrics|checks:metrics_aggregate",
    "TC-L4-003": "exec:metrics|checks:metrics_aggregate",
    "TC-L4-004": "exec:metrics|manual:人工送达率L3",
    "TC-L4-005": "exec:metrics|checks:metrics_aggregate",
    "TC-L4-006": "exec:metrics|manual:未命中追踪汇总",
}
